using Raven.Client.Documents;
using Raven.Client.Documents.Session;
using RavenDB.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RavenDB
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var documentStore = DocumentStoreHolder.Store)
            {
                // The Session is used to manipulate the data. It implements the Unit of Work pattern and is capable of batching the requests to save expensive remote calls.
                // In contrast to a DocumentStore it is a lightweight object and can be created more frequently.
                // For example, in web applications, a common (and recommended) pattern is to create a session per request.
                using (var session = documentStore.OpenSession())
                {
                    // Example I - Storing 
                    
                    Category category = new Category
                    {
                        Name = "Database Category"
                    };

                    session.Store(category);

                    Product product = new Product
                    {
                        Name = "RavenDB Database",
                        Category = category.Id,
                        UnitsInStock = 10
                    };

                    session.Store(product);

                    session.SaveChanges();

                    // Example II - Loading

                    product = session
                        .Include<Product>(x => x.Category)
                        .Load(product.Id);

                    category = session
                        .Load<Category>(product.Category);

                    product.Name = "RavenDB";
                    category.Name = "Database";

                    session.SaveChanges();

                    // Example III - Querying

                    List<string> productNames = session
                        .Query<Product>()
                        .Where(x => x.UnitsInStock > 5)
                        .Skip(0).Take(10)
                        .Select(x => x.Name)
                        .ToList();

                    // Examples from Per.

                    // Load or Query RavenDB.
                    Employee employee = session.Load<Employee>("employees/1-A");
                    List<Employee> employees = session.Query<Employee>().Where(e => e.FirstName == employee.FirstName).ToList();

                    // Change the name of the employee.
                    employee.FirstName = "NewName";

                    session.SaveChanges();

                    employees = session
                        .Query<Employee>()
                        .Where(x => x.FirstName == "Robert")
                        .ToList();

                    List<string> lastNames = session
                        .Query<Employee>()
                        .Where(x => x.Birthday > new DateTime(1960, 1, 1))
                        .Select(x => x.LastName)
                        .ToList();

                    // Create an employee with an autogenerated Id.
                    Employee newEmployee = new Employee
                    {
                        LastName = "Contenti",
                        FirstName = "Alessia",
                        Address = new Address
                        {
                            City = "Jelling",
                            Line1 = "Bethaniavej 2",
                            Region = "Syddanmark",
                            Country = "Denmark",
                            Location = new Location
                            {
                                Latitude = 50,
                                Longitude = 50
                            }
                        },
                        Birthday = new DateTime(1996, 03, 02)
                    };

                    session.Store(newEmployee);
                    session.SaveChanges();

                    // Create an employee with a specific Id.
                    employee = new Employee
                    {
                        Id = "01",
                        LastName = "Contenti",
                        FirstName = "Alessia",
                        Address = new Address
                        {
                            City = "Jelling",
                            Line1 = "Bethaniavej 2",
                            Region = "Syddanmark",
                            Country = "Denmark",
                            Location = new Location
                            {
                                Latitude = 50,
                                Longitude = 50
                            }
                        },
                        Birthday = new DateTime(1996, 03, 02)
                    };

                    session.Store(newEmployee, "TestInput");
                    session.SaveChanges();

                    Console.WriteLine("Hello world!");
                }
            }
        }
    }
}
